============================================================================================== 
Warning! Mixing Conda and module environments may lead to corruption of the
user environment. 
We do not recommend users mixing those two environments unless absolutely
necessary. Note that 
SURF does not provide any support for Conda environment.
For more information, please refer to our software policy page:
https://servicedesk.surf.nl/wiki/display/WIKI/Software+policy+Snellius#SoftwarepolicySnellius-UseofAnacondaandMinicondaenvironmentsonSnellius 

Remember that many packages have already been installed on the system and can
be loaded using 
the 'module load <package__name>' command. If you are uncertain if a package is
already available 
on the system, please use 'module avail' or 'module spider' to search for it.
============================================================================================== 
Already up to date.
Obtaining file:///gpfs/home6/jhuizing/master-thesis-ds/ptdraft
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Checking if build backend supports build_editable: started
  Checking if build backend supports build_editable: finished with status 'done'
  Getting requirements to build editable: started
  Getting requirements to build editable: finished with status 'done'
  Preparing editable metadata (pyproject.toml): started
  Preparing editable metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: sisa3d
  Building editable for sisa3d (pyproject.toml): started
  Building editable for sisa3d (pyproject.toml): finished with status 'done'
  Created wheel for sisa3d: filename=sisa3d-0.1.0-py3-none-any.whl size=1286 sha256=466689da9623440a694956c93a4920038d607a9428abb993da0c7549d07f4ef9
  Stored in directory: /gpfs/scratch1/nodespecific/gcn20/jhuizing.6335937/pip-ephem-wheel-cache-zuv3jvbc/wheels/ba/24/02/45c17a515af0a22326616b14da79c51e525e740ad6f0b007df
Successfully built sisa3d
Installing collected packages: sisa3d
  Attempting uninstall: sisa3d
    Found existing installation: sisa3d 0.1.0
    Uninstalling sisa3d-0.1.0:
      Successfully uninstalled sisa3d-0.1.0
Successfully installed sisa3d-0.1.0
[INFO] Creating temporary directory for config files: tmp_configs
Generated 10 configuration files in tmp_configs.
[INFO] ✅ Temporary directory created with config files: tmp_configs
[INFO] Running sequantial grid search with 10 configuration files...
Running grid search:   0%|          | 0/10 [00:00<?, ?it/s][INFO] Running pipeline with config: tmp_configs/temporary_8.config.yaml
[INFO] Loading configuration...
[INFO] ✅ Configuration loaded.
[INFO] Loading paths...
[INFO] ✅ Paths loaded.
[INFO] Creating paths if they don't exist...
[INFO] ✅ Paths created.
[INFO] Initializing preprocessing pipeline...
[INFO] Running preprocessing pipeline...
[INFO] ✅ Preprocessing pipeline complete.
[INFO] Running DreamGaussian Stage 1 pipeline...
[INFO] ✅ DreamGaussian pipeline complete.
[INFO] Running Evaluation pipeline...
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:01<00:00,  1.68s/it]100%|██████████| 1/1 [00:01<00:00,  1.72s/it]
  0%|          | 0/1 [00:00<?, ?it/s]100%|██████████| 1/1 [00:00<00:00,  1.55it/s]100%|██████████| 1/1 [00:00<00:00,  1.43it/s][ERROR] ❌ Error in pipeline: 'list' object has no attribute 'item'

Traceback (most recent call last):
  File "pipeline.py", line 140, in <module>
    raise e
  File "pipeline.py", line 94, in <module>
    clip_scores = compute_clip_scores(f"{STAGE_1_IMAGES_PATH}generated", f"{STAGE_1_IMAGES_PATH}reference").item()
AttributeError: 'list' object has no attribute 'item'
[ERROR] ❌ Subprocess error with non-zero exit status 1 for config: tmp_configs/temporary_8.config.yaml
Running grid search:   0%|          | 0/10 [02:23<?, ?it/s]
Traceback (most recent call last):
  File "grid_search.py", line 67, in <module>
    run_pipeline(config_path)
  File "grid_search.py", line 38, in run_pipeline
    raise cpe
  File "grid_search.py", line 30, in run_pipeline
    subprocess.run(["python", "pipeline.py", "--config", config_path], check=True)
  File "/home/jhuizing/.conda/envs/dreamgaussianV2/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'pipeline.py', '--config', 'tmp_configs/temporary_8.config.yaml']' returned non-zero exit status 1.

JOB STATISTICS
==============
Job ID: 6335937
Cluster: snellius
User/Group: jhuizing/jhuizing
State: FAILED (exit code 1)
Nodes: 1
Cores per node: 18
CPU Utilized: 00:02:50
CPU Efficiency: 3.73% of 01:15:54 core-walltime
Job Wall-clock time: 00:04:13
Memory Utilized: 3.24 GB
Memory Efficiency: 2.70% of 120.00 GB
